setwd("C:\\Users\\murhar.family\\Desktop\\coursera\\Explore_data_analysis\\week1_project\\power_consump")
data<-read.table("household_power_consumption.txt", header=TRUE,sep=";",stringsAsFactors=FALSE)
req_data<-subset(data,Date %in% c("1/2/2007","2/2/2007"))
cmplt_date_time <- strptime(paste(req_data$Date, req_data$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
global_act_power<-as.numeric(req_data$Global_active_power)
req_data$Voltage<-as.numeric(req_data$Voltage)
req_data$Global_reactive_power<-as.numeric(req_data$Global_reactive_power)
png("plot4.png",height = 480,width = 480)
par(mfrow=c(2,2))
plot(cmplt_date_time,global_act_power, type = "l",ylab = "Global Active Power (kilowatts)",xlab = "")
plot(cmplt_date_time,req_data$Voltage,type = "l",ylab = "Voltage(volt)",xlab = "datetime")
plot(cmplt_date_time,req_data$Sub_metering_1,type = "l",ylab = "Energy Sub Metering",xlab = "")
lines(cmplt_date_time,req_data$Sub_metering_2,col="red")
lines(cmplt_date_time,req_data$Sub_metering_3,col="blue")
legend("topright",legend = c("sub_metering1","sub_metering2","sub_metering3"),col = c("black","red","blue"),lty = 1,lwd=2)
plot(cmplt_date_time,req_data$Global_reactive_power,type="l",ylab = "Golbal reactive power(kilowatts)",xlab="datetime")
dev.off